### ISSUE TITLE
FB createDataset.py

### ISSUE THREAD

**Issue by holmstrom** [adeshpande3/Facebook-Messenger-Bot#11]
Hello, 

Would it be possible to see an example, of the way, the script for making the createDataset.py should look like? 
I am getting a few errors, when I try to set it up. 

I have changed the file name, but I still won't let it pass.

**Comment by adeshpande3** [comment]
Not sure where you're getting stuck, is it a problem with obtaining the data or running createDataset.py, or ??? Maybe just describe what errors you're getting. And also be sure to take a look at the README

**Comment by holmstrom** [comment]
When I am editing the createDataset.py to settings, it first of all give me the error '  File "createDataset.py", line 26
    for index,lines in enumerate(allLines):
                                          ^
TabError: inconsistent use of tabs and spaces in indentation' at the Googlehangout data. 

The only data I want to use is the Facebookdata. But I can not seem to get it running. It gives me an error every time, either I get the error "SyntaxError: Missing parentheses in call to 'print'" or another syntax error. 

So I was wondering if you could put up an example, where everything is put up correctly. 

I know it should be super simple, but I just can not figure out this step.

**Comment by adeshpande3** [comment]
So the TabError that you're experiencing is more of a Python specific issue. It refers to an error that occurs when your code isn't aligned correctly in your editor. So when you were making changes to createDataset.py, there might've been some changes to that alignment. And the error with the parentheses is just a difference between Python 2 and Python 3, where Python 3 requires parentheses in the print statement while Python 2 does not. 

The example where everything is put up correctly is the unmodified createDataset.py so not sure what other piece of code you're looking for.

**Comment by holmstrom** [comment]
Aha, that makes sense! 

I know, I am asking a lot of stupid questions. I just have hard time of finding out these simple issues. 
For example I get this error 
"File "<ipython-input-5-c61c1d654257>", line 119
    conversationFile.write(key.strip() + value.strip())
                                                       ^
TabError: inconsistent use of tabs and spaces in indentation" 

Where do I need to insert parentheses in that sentence?

**Comment by adeshpande3** [comment]
Don't worry about it! Everyone starts off asking these types of questions, it's the best way to learn. For that TabError, it's not that you need to insert parentheses (that was for the print statements), but you need to make sure that all your spaces/tabs are of the correct lengths in each code block. This [link](http://www.secnetix.de/olli/Python/block_indentation.hawk) may give you some useful info.

**Comment by holmstrom** [comment]
Thank you. 
I tried to run it by using Anaconda 2.7, and that worked - thanks!
