### ISSUE TITLE
Data Dictionary Contentless!

### ISSUE THREAD

**Issue by Bharghvi** [adeshpande3/Facebook-Messenger-Bot#12]
After running createDatabase.py, My conversationData.txt is empty! Can you please guess the reason?

Thank You

**Comment by adeshpande3** [comment]
Be sure to read the [README](https://github.com/adeshpande3/Facebook-Messenger-Bot/blob/master/README.md) and make sure that you've downloaded the correct data and you have it in the files fbMessages.txt, Inbox.csv, and the GoogleTextForm folder. You may also want to print your contents of combinedDictionary to make sure that the messages are getting added.

**Comment by mzjp2** [comment]
I had the same thing happen to me - turned out that it was an issue with my python indenting. Make sure that the indents match the ones in the repo perfectly.

**Comment by saurabh-rao** [comment]
I can speak for the linkedin bit : 

Had the same issue  as @Bharghvi . Scrapy just kept throwing up login errors . Tried it with [this ](https://github.com/arielscarpinelli/linkedin-inbox-exporter) as well , had the same issue. 

I'm assuming it is an issue with linkedin , and not with the code written. I had better luck downloading my linkedin data by getting to the website . Took like a min and had the same output.
