### ISSUE TITLE
Multiple syntax errors when trying to run "Word2Vec.py"

### ISSUE THREAD

**Issue by 0HelloAlice** [adeshpande3/Facebook-Messenger-Bot#13]
I have 0 clue why it refuses to run. tried running it with all the requirements in a python 3.6 environment in anaconda and a 2.7 environment. Everything appears to match up, and honestly I'm thoroughly stumped being slightly new to python. Can't tell if there's anything missing either, but for comparative reasons I'll paste the whole thing.

import tensorflow as tf 
import numpy as np 
import re
from collections import Counter
import sys
import math
from random import randint
import pickle
import os

wordVecDimensions = 100
batchSize = 128
numNegativeSample = 64
windowSize = 5
numIterations = 100000

def processDataset(filename):
	openedFile = open(filename, 'r')
	allLines = openedFile.readlines()
	myStr = ""
	for line in allLines:
	    myStr += line
	finalDict = Counter(myStr.split())
	return myStr, finalDict

def createTrainingMatrices(dictionary, corpus):
	allUniqueWords = dictionary.keys()	
	allWords = corpus.split()
	numTotalWords = len(allWords)
	xTrain=[]
	yTrain=[]
	for i in range(numTotalWords):
		if i % 100000 == 0:
			print ('Finished %d/%d total words' % (i, numTotalWords)
(wordsAfter) == allWords[i + 1:i + windowSize + 1]
(wordsBefore) == allWords[max(0, i - windowSize):i]
		 wordsAdded = wordsAfter + wordsBefore
                 for word in (wordsAdded):
		xTrain.append(allUniqueWords.index(allWords[i]))
		yTrain.append(allUniqueWords.index(word))
	return xTrain, yTrain

def getTrainingBatch():
	num = randint(0,numTrainingExamples - batchSize - 1)
	arr = xTrain[num:num + batchSize]
	labels = yTrain[num:num + batchSize]
	return arr, labels[:,np.newaxis]

continueWord2Vec = True
if (os.path.isfile('Word2VecXTrain.npy') and os.path.isfile('Word2VecYTrain.npy') and os.path.isfile('wordList.txt')):
	xTrain = np.load('Word2VecXTrain.npy')
	yTrain = np.load('Word2VecYTrain.npy')
	print ('Finished loading training matrices')
	with open("wordList.txt", "rb") as fp:
		wordList = pickle.load(fp)
	print ('Finished loading word list')

else:
	fullCorpus, datasetDictionary = processDataset('conversationData.txt')
	print ('Finished parsing and cleaning dataset')
	wordList = datasetDictionary.keys()
	createOwnVectors = raw_input('Do you want to create your own vectors through Word2Vec (y/n)?')
	if (createOwnVectors == 'y'):
		xTrain, yTrain  = createTrainingMatrices(datasetDictionary, fullCorpus)
		print ('Finished creating training matrices')
		np.save('Word2VecXTrain.npy', xTrain)
		np.save('Word2VecYTrain.npy', yTrain)
	else:
		continueWord2Vec = False
	with open("wordList.txt", "wb") as fp: 
		pickle.dump(wordList, fp)

**Comment by adeshpande3** [comment]
If I'm not mistaken, I don't think this print statement has a closing parenthesis

![image](https://user-images.githubusercontent.com/13543909/35834952-df3bbd24-0a8c-11e8-9340-b970f1e26dbe.png)

**Comment by 0HelloAlice** [comment]
I just noticed that actually, but after doing that I get a the same error here 
![screenshot 97](https://user-images.githubusercontent.com/36176120/35835179-4086f066-0aa7-11e8-85f8-4cc93f5d3948.png)

**Comment by adeshpande3** [comment]
I think you need another one after numTotalWords, in order to close the one started before 'Finished'. So, it would be like the following

print ('Finished %d/%d total words' % (i, numTotalWords))

**Comment by 0HelloAlice** [comment]
Fixed all the punctuation, seemed to run but then spat out a unicodedecode error at me. appreciate the pointers by the way, super helpful
![screenshot 98](https://user-images.githubusercontent.com/36176120/35835520-2a0f7a22-0aa9-11e8-9bf1-77ed3e7c4fbf.png)

**Comment by adeshpande3** [comment]
I think changing this line 
`openedFile = open(filename, 'r')`
to
`openedFile = open(filename, 'r', encoding="utf-8")`
might work. If not, I'd recommend looking through the search results [here](https://www.google.com/search?q=charmap%27+codec+can%27t+encode+character&oq=char+map+cant+&aqs=chrome.3.69i57j0l4j69i64.4727j0j1&sourceid=chrome&ie=UTF-8)

**Comment by 0HelloAlice** [comment]
Changing the encoding resolved that error. It'll let me select an input option for making the vectors but then this'll happen. looked on stackoverflow but didn't really find anything useful
![screenshot 99](https://user-images.githubusercontent.com/36176120/35894315-0fd752a6-0b80-11e8-85b4-2fdf9e5a73e2.png)

**Comment by adeshpande3** [comment]
[This](https://stackoverflow.com/questions/18552001/accessing-dict-keys-element-by-index-in-python3) link will help. Basically, it's saying that if you're using Python3, you should use 
`allUniqueWords = list(dictionary)`
instead of 
`allUniqueWords = dictionary.keys()`

**Comment by Moriartywasreal** [comment]
After making all of the changes above I am still stuck at
Traceback (most recent call last):
  File "Word2Vec.py", line 82, in <module>
    pickle.dump(wordList, fp)
TypeError: can't pickle dict_keys objects

Python 3.6.4
win 8

**Comment by adeshpande3** [comment]
Not completely sure, but likely is an issue with Python3 and the way you pickle a list. Make sure you also take a look at the latest commits for that code because I think I changed line 72 a little while ago, and that might fix the issue.
