### ISSUE TITLE
Syntax error in Seq2Seq.py

### ISSUE THREAD

**Issue by Fleker** [adeshpande3/Facebook-Messenger-Bot#19]
https://github.com/adeshpande3/Facebook-Messenger-Bot/blob/master/Seq2Seq.py#L145

I'm getting a syntax error on this line:

`if (os.path.isfile('embeddingMatrix.npy'):`

**Comment by Fleker** [comment]
There's a similar error in line 156

**Comment by adeshpande3** [comment]
Thanks for that catch.
