### ISSUE TITLE
Issue with Word2Vec.py

### ISSUE THREAD

**Issue by cadarsh88** [adeshpande3/Facebook-Messenger-Bot#2]
"_pickle.PicklingError: Can't pickle <class 'dict_keys'>: attribute lookup dict_k
eys on builtins failed"

Am sorry about the ignorance, but, can't completely verify the error. Any guidance would be much appreciated. I am running on windows, if that will be an issue here. Please suggest a workaround.

**Comment by adeshpande3** [comment]
Are you getting this error at line 65? Have you run createDataset.py first, and created that wordsList.txt file?

**Comment by cadarsh88** [comment]
Thanks man! 
I could resolve that. Changed dictionary to list data type.
