### ISSUE TITLE
error in Word2Vec.py when running in python 3.6.4

### ISSUE THREAD

**Issue by Moriartywasreal** [adeshpande3/Facebook-Messenger-Bot#23]
I modified the code to run in 3.x but I'm still getting the following error:
Traceback (most recent call last):
  File "Word2Vec.py", line 82, in <module>
    pickle.dump(wordList, fp)
TypeError: can't pickle dict_keys objects

**Comment by adeshpande3** [comment]
Not completely sure, but likely is an issue with Python3 and the way you pickle a list. Might be differnt from Python 2. Make sure you also take a look at the latest commits for that code because I think I changed line 72 a little while ago, and that might fix the issue.

**Comment by Moriartywasreal** [comment]
I made the following changes
line no: 28  openedFile = open(filename, 'r',encoding="latin-1") //added encoding
             37 allUniqueWords = list(dictionary) //use of list
             72 wordList =  list(datasetDictionary.keys()) 
and the print() statements.
Now it works.
Thanks!!
Also I am trying to train using (the Harry Potter scripts) as Harry...as i use a lot of words in my mother tongue in my chats.
Awesome work.
