### ISSUE TITLE
Compilation errors on Seq2Seq.py

### ISSUE THREAD

**Issue by baalajimaestro** [adeshpande3/Facebook-Messenger-Bot#32]

**Comment by adeshpande3** [comment]
What are the errors that you're getting?

**Comment by baalajimaestro** [comment]
I am getting errors on randint function in `def getTrainingBatch(localXTrain, localYTrain, localBatchSize, maxLen):
	num = randint(0,numTrainingExamples - localBatchSize - 1)
	arr = localXTrain[num:num + localBatchSize]`
Coz the randint must have second parameter higher than first it threw me an exception

And on modifying it to `def getTrainingBatch(localXTrain, localYTrain, localBatchSize, maxLen):
	num = randint(0,abs(numTrainingExamples - localBatchSize - 1))
	arr = localXTrain[num:num + localBatchSize]'
Doesn't help it either

It instead sends back empty lists

**Comment by adeshpande3** [comment]
If the 2nd parameter is lower than the first, then that means that "numTrainingExamples - localBatchSize - 1" returns you a negative value. 

Check what your values for numTrainingExamples and localBatchSize are. Batch size should always be less than the number of training examples.

**Comment by adeshpande3** [comment]
So the number of training examples shouldn't be 0. It should be a positive number. Check where that value is getting initialized (most likely in createTrainingMatrices) and why it's 0.
