### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by o55665516** [adeshpande3/Facebook-Messenger-Bot#33]
I have this error "TypeError: list indices must be integers or slices, not tuple"
How can I change it?
And below is my code
![image](https://user-images.githubusercontent.com/11363415/43038140-c3044350-8d46-11e8-97ed-82d2e40f218e.png)

**Comment by o55665516** [comment]
that say error in line 57

**Comment by adeshpande3** [comment]
There is likely a problem with the dimensions of your data structures. xTrain and yTrain should both be arrays of shape (x,) where x is the number of examples you have. 

And the shapes of two arrays that get returned (arr and labels) should be (b,) and (b,1) respectively where b is the batch size.

**Comment by Paradoxdruid** [comment]
I fixed this by changing line 57 to:
`return arr, np.array(labels)[:,np.newaxis]`

(it needs to be reformatted as an array to be sliced correctly)

**Comment by adityamangal1998** [comment]
chane it to
return (arr, labels[:,np.newaxis])
it is worked for me ,i am using python 3.6
