### ISSUE TITLE
fbcap : command not found error

### ISSUE THREAD

**Issue by Hitarth01** [adeshpande3/Facebook-Messenger-Bot#4]
All steps are followed but after cloning the fb parser repo the command following it shows the following error 
![error](https://user-images.githubusercontent.com/20516641/30171185-3af024a4-9402-11e7-919c-4ded5fbb89d8.png)

**Comment by adeshpande3** [comment]
Check out the updated instructions in the README. You're supposed to clone another directory, cd into it, and then run the command. Once the command is run, you'll move the newly created fbMessages.txt file to your Facebook-Messenger-Bot folder.

**Comment by Hitarth01** [comment]
![error](https://user-images.githubusercontent.com/20516641/30179237-bcc8d394-941c-11e7-8644-33aabd4a4de6.png)

Hey thanks for helping out but i am still facing the same problem.

**Comment by adeshpande3** [comment]
Oops sorry, wrong instructions. Instead of cloning the repo, just do a pip install of his tool. Take a look at the updated README or the [README](https://github.com/ownaginatious/fbchat-archive-parser) for the tool itself.

**Comment by Hitarth01** [comment]
Thanks for helping out again but i am still facing the same issue.
Is it a problem because of the Windows OS?
I am currently using the Git Bash on Windows.

**Comment by adeshpande3** [comment]
Not sure. I think for those questions, you should just open an issue on Dillon's [repo](https://github.com/ownaginatious/fbchat-archive-parser)

**Comment by Hitarth01** [comment]
Cool thanks for helping out great repo :)
