### ISSUE TITLE
compilation error in seq2seq.py

### ISSUE THREAD

**Issue by srinivas175** [adeshpande3/Facebook-Messenger-Bot#43]
@adeshpande3 , I get a compilation error saying:
ValueError: empty range for randrange() (0,-24, -24)
my localBatchSize = 24 and numTrainingExamples=0.
I don't understand why numTrainingExamples is returning zero.
the line 176 'numTrainingExamples = xTrain.shape[0]' returns zero. Can you please help in solving this issue?
thanks in advance

**Comment by adeshpande3** [comment]
Have you run createDataset.py yet? In order for createTrainingExamples to return you a nonempty xTrain, you need to have the conversationDictionary.npy and conversationData.txt files. Take a look at the steps in the [Readme](https://github.com/adeshpande3/Facebook-Messenger-Bot/blob/master/README.md) again.

**Comment by srinivas175** [comment]
@adeshpande3  I've run the createDataset.py. The conversationDictionary.npy and conversationData.txt files were created successfully.

**Comment by adeshpande3** [comment]
So you want to probably take a look at the different functions in createDataset.py (getWhatsAppData, getFacebookData, etc) and see what each of their response dictionaries is returning. Something with the data format may have changed, and thus the parsing may be incorrect.

**Comment by srinivas175** [comment]
@adeshpande3 I've used the getWhatsAppData in mine. 
In the dict, 
the line "responseDictionary[otherPersonsMessage.rstrip()] = myMessage.rstrip()" just adds mymessages to the dict and not friend's messages.
the total length of the dictionary is returning 1.
The  conversationDictionary.npy is not having (FRIENDS_MESSAGE, YOUR RESPONSE) pairs

**Comment by adeshpande3** [comment]
Okay I see, so I guess it's an issue with the logic of the parsing. Unfortunately I didn't write that section of the code, another Github user submitted it but they seem to have deleted their account so I don't think I can contact them. Currently don't have the time to look into it (earliest I can take a look is tomorrow), but if you find a fix, feel free to submit a PR and I can merge it.

**Comment by srinivas175** [comment]
@adeshpande3 , Ok I'll look into it. Thanks for the quick response!!

**Comment by srinivas175** [comment]
@adeshpande3 I've sorted out the problem and fixed it. As predicted by you, there is a small parser problem in the getWhatsappData() that generates the error. The data from the pandas dataframe is not transferred to the responseDictionary dict.

**Comment by srinivas175** [comment]
I'll post the modified getWhatsappData() function here. I've solved the parsing issue and parse the data into conversationDictionary.npy correctly which ultimately resolves the error mentioned here : https://github.com/adeshpande3/Facebook-Messenger-Bot/issues/43#issue-448427959.
In the code, I've haven't used the cleanMessage function. 

`   
    def getWhatsAppData():

    df = pd.read_csv('whatsapp_chats.csv')

    responseDictionary = dict()

    receivedMessages = df[df['From'] != personName]

    sentMessages = df[df['From'] == personName]

    sent = sentMessages['Content']

    received = receivedMessages['Content']

    sent = sent.rename(columns={'Content': 'YOUR_RESPONSE'})

    received = received.rename(columns={'Content': 'FRIENDS_MESSAGE'})

    combined = pd.concat([tx, rx], axis=1)

    x = combined.to_csv('traindata.csv',index=False)

    return combined

 combinedDictionary =dict()
  if (whatsAppData == 'y'):
        print('Getting whatsApp Data')
        p = getWhatsappData()
        combinedDictionary=dict(p.values)

  print 'Total len of dictionary', len(combinedDictionary)
 
  print 'Saving conversation data dictionary'
  np.save('conversationDictionary.npy', combinedDictionary)
