### ISSUE TITLE
getData() for Discord logs

### ISSUE THREAD

**Issue by TotallyNotChase** [adeshpande3/Facebook-Messenger-Bot#49]
I think to improve the functionality and increase the dataset, the scan should include discord messages too. The user can simply get their discord chat logs from [this exporter](https://github.com/Tyrrrz/DiscordChatExporter), much the same way they get their other chatlogs.

I already have some `regex` ready to parse through the whole log, tried and tested, efficient and fast. The regex collects **one or multiple responses (of the given username) for each message (of someone that is not the user)**. This will obviously work best in direct messages but it can definitely *work* on servers too. 

Let me know if you'd like this feature to be implemented :D @adeshpande3

**Comment by adeshpande3** [comment]
Hey, thanks for the suggestion and the offer! I'm not maintaining this as much as I have in previous years, but I'd definitely be open to reviewing a PR and adding this functionality if you're excited to take it on. 

Would honestly help to have some other people supporting/maintaining since I haven't taken a hard look at the code in a year or two.

**Comment by TotallyNotChase** [comment]
@adeshpande3 No worries, if you could just confirm whether or not I'm allowed to use `regex` (i.e `import re`), I'll get on it immediately.

**Comment by adeshpande3** [comment]
Yeah I don't see a problem with that. Just to confirm, we'd create a function `getDiscordData()` which will read in the chat logs file that will come out of the exporter, and return a dictionary that maps from other person's response -> your response? 

(Just realized this whole dictionary approach is kind of problematic since it doesn't allow you to represent different responses for a single prompt - ugh the perils of reading your own code a few years later 😢)

Open to larger refactor LOL but yeah, confirming your function would work like that?

**Comment by TotallyNotChase** [comment]
That is exactly it!, the `value` (s) in that dictionary will end up being a list, because `you` can have multiple responses to the other person's singular `message` . 

Consider we feed a chat log that looks like this-

![image](https://user-images.githubusercontent.com/44284917/72867366-ae339100-3d04-11ea-99d4-90b4a34c942d.png)
This is how it'd look like in the dict (note that this is just a `.json` file I exported)

![image](https://user-images.githubusercontent.com/44284917/72867216-36fdfd00-3d04-11ea-950c-dbd881efba41.png)

Where the `key`(s) are the other person's singular `message` and the `value` (s) are my `response` (s)

**Comment by TotallyNotChase** [comment]
ahhh on second thought, looks like all the other datasets don't use multiple `myMessage` for each `otherPersonsMessage` so implementing that will take quite a lot of changes. I think I'd rather implement it so that it's streamlined with all the other `get....Data()`

Let me know if that's fine, I'll make a PR for you to review right afterwards. If you'd like I can totally help as best as I can maintaining this project (since it's quite cool) and first and foremost I'd upgrade the whole project to python 3, since otherwise I can't use `tensorflow` on windows.

**Comment by TotallyNotChase** [comment]
@adeshpande3 Some progress update, the upgradation from python 2 to 3 is almost done. There's some fairly big changes so perhaps the model creation could be overhauled but right now I've managed to get it to support `python 3` and `tensorflow==2.1.0` while keeping the model the same. 

I suppose I should make a PR for just the `getDiscordData()` for now. I'm just waiting on your response to my previous comment explaining my implementation :)

**Comment by adeshpande3** [comment]
Apologies for the late reply. I think the mapping from string to list of strings is definitely the right approach (one that I should've taken when I created this). I would be fine with a couple approaches:

1. Having that `getDiscordData()` function be slightly different in returning the list and then making sure that the later processing is robust to both. Would probably need to change how `combinedDictionary` is getting created. 
2. Having `getDiscordData()` be similar to the other methods in just a 1:1 mapping. 
3. Refactor other methods to also have the string to list of strings form + implement `getDiscordData()` in the way you were talking about.

**Comment by TotallyNotChase** [comment]
@adeshpande3 Awesome! I'm going with **approach 2** right now but I'm absolutely going to be working on **approach 3** if you'd like me to! Right now I'm focusing on getting it to be ready and working with `python 3`. 

I made a [PR](https://github.com/adeshpande3/Facebook-Messenger-Bot/pull/50) for just **approach 2** `getDiscordData()` for now!

**Comment by adeshpande3** [comment]
Took a high level pass and things look good. Bit swamped rn but will take a closer look tomorrow morning. 

Thanks for this work!
