### ISSUE TITLE
error while running seq2seq.py

### ISSUE THREAD

**Issue by mayanksingh1998** [adeshpande3/Facebook-Messenger-Bot#57]
Traceback (most recent call last):
  File "Seq2Seq.py", line 226, in <module>
    encoderTrain, decoderTargetTrain, decoderInputTrain = getTrainingBatch(xTrain, yTrain, batchSize, maxEncoderLength)
  File "Seq2Seq.py", line 56, in getTrainingBatch
    num = randint(0,numTrainingExamples - localBatchSize -1)
  File "/home/mayank/anaconda3/envs/mayank/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/mayank/anaconda3/envs/mayank/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-24, -24)

if i add +25 in this as  num = randint(0,numTrainingExamples - localBatchSize -1 +25 )
then a new error comes as follows

Traceback (most recent call last):
  File "Seq2Seq.py", line 227, in <module>
    feedDict = {encoderInputs[t]: encoderTrain[t] for t in range(maxEncoderLength)}
  File "Seq2Seq.py", line 227, in <dictcomp>
    feedDict = {encoderInputs[t]: encoderTrain[t] for t in range(maxEncoderLength)}
IndexError: list index out of range

please tell me its really important

**Comment by TotallyNotChase** [comment]
Just to confirm, you are using the code from `master` branch correct?
Back to the original question, it seems the data being fed in is wrong. This has not happened to me yet so the only way to know what's wrong is to check the passed in values in debug mode. 

Could you tell me, step by step, what you did? perhaps I can reproduce this

**Comment by mayanksingh1998** [comment]
Actually the thing is i want to train on my whatsapp chats and the link given to change the whatsapp chat to csv file in the readme is not working so i used a different script for that 

can you please tell me how to train this on whatsapp chat data or how to convert the whatsapp chats to csv file so that no error come

**Comment by TotallyNotChase** [comment]
I see, that's a valid concern. Could you try using [this parser](https://github.com/Pustur/whatsapp-chat-parser) and report your findings? If it works, great! I'll change up the link. If it doesn't, I'll make sure to change up our library's method to work with that parser.

**Comment by mayanksingh1998** [comment]
the parser you have specified now is not the parser which will change chats.txt to chats.csv it only shows the chats.txt with a UI like whatsapp

**Comment by TotallyNotChase** [comment]
@mayanksingh1998 noted, that's my bad. Will most probably have to rework the whatsapp parse method. 

Patching @adeshpande3 through to confirm what to do.

I'm thinking of going through the `.txt` files that whatsapp lets you download and then extracting the response sets. I see 2 ways to do that off the top of my head-
* Do it like `getGoogleHangoutsData` -> Just normal iteration, look for `:` after a name and a timestamp and then fetch the message

* Do it like `getDiscordData` -> Use some sophisticated regex to directly fetch the response sets

I might be able to get one of those done by tomorrow (the 28th). Are you fine with reworking the method? @adeshpande3

**Comment by adeshpande3** [comment]
Sorry for the late reply, taking a look.

**Comment by adeshpande3** [comment]
Yeah that's fine by me (either normal iteration or regex is fine, whatever is more comfortable for you!). It would be backward compatible here and keep the functionality for CSV versions of the data (probably do some sort of check to see what type of file the user has).
