### ISSUE TITLE
Empty dictionary on running CreateDataset.py

### ISSUE THREAD

**Issue by mayanksingh1998** [adeshpande3/Facebook-Messenger-Bot#59]
I have placed the chat.txt file in specified folder i.e WhatsappChatLogs but after running the script CreateDataSet.py the outcome is null i.e dictionary size is 0 and also ConversationData.txt which is created on running createdataset.py is also empty

Following output is coming
Do you have Facebook data to parse through (y/n)?n
Do you have Google Hangouts data to parse through (y/n)?n
Do you have LinkedIn data to parse through (y/n)?n
Do you have whatsAppData to parse through (y/n)?y
Do you have discordData to parse through (y/n)?n
Getting whatsApp Data
Enter your full WhatsApp name: Manju
Total len of dictionary 0
Saving conversation data dictionary

**Comment by TotallyNotChase** [comment]
Could you post a small part of the chat.txt file? You can replace the messages for your privacy, just need to check the format

**Comment by mayanksingh1998** [comment]
there was a small change in the script instead of finding the "] " we have to find "- " 
I have changed it
Can i upload it to the repository

**Comment by TotallyNotChase** [comment]
Strange, it seems the chats come in different formats? The format I was working with looked like this-
>[20.06.19, 15:58:57] Loris: Welcome to the chat example
>[20.06.19, 15:59:07] John: Thanks

Before changing anything, we need to make sure the format in use is correct. Could you post an example of what the format looks like to you?

**Comment by mayanksingh1998** [comment]
12/28/19, 21:43 - Loris: Welcome to the chat example
12/28/19, 21:43 - John: Thanks

**Comment by TotallyNotChase** [comment]
Weird, those are very different formats.

@adeshpande3 Could you please check what format your whatsapp chats export to?

If there are different results, for apparently unknown reasons, I'll have to come up with a unified solution for all the formats to work.

**Comment by mayanksingh1998** [comment]
Can you please help me in making a simple input and output programme for the trained model without making any server or with server am not able to do this.

**Comment by TotallyNotChase** [comment]
@mayanksingh1998 That's offtopic for this particular issue, you should consider reading the steps mentioned in README and then open an issue for the particular thing you don't understand. The owner will be able to help you on that.

If you want to just make a simple program to test out the chatbot. You can probably set up a server on your localhost and let that use the model. Then make a frontend to communicate with that server. The code for a flask server is mentioned in the README, [here](https://github.com/adeshpande3/Chatbot-Flask-Server) it is!

**Comment by mayanksingh1998** [comment]
thanks but i tried but can't able to do this

**Comment by TotallyNotChase** [comment]
This should be fixed in the latest update. Added support for both formats.
