### ISSUE TITLE
Claiming to not be able to find numpy module despite it being installed

### ISSUE THREAD

**Issue by grandmoffgigi** [adeshpande3/Facebook-Messenger-Bot#61]
`Traceback (most recent call last):
  File "createDataset.py", line 3, in <module>
    import pandas as pd
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\__init__.py", line 56, in <module>
    import pandas.util.testing
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\util\testing.py", line 22, in <module>
    from numpy.testing.decorators import slow     # noqa
ModuleNotFoundError: No module named 'numpy.testing.decorators'`
What I found on this said it was caused by not having numpy, yet I do have it,

**Comment by TotallyNotChase** [comment]
Did you make sure `numpy` is installed inside `C:\Program Files\Anaconda3\`? Perhaps you've it installed somewhere else but not there. 

Also make sure you've `numpy == 1.16.4`

**Comment by grandmoffgigi** [comment]
It was in `C:\Program Files\Anaconda3\Lib\site-packages` so yes. 

Scikit and Scipy were already installed and updated, as was numpy.

**Comment by TotallyNotChase** [comment]
I noticed you're using anaconda3, which is meant for python3. This project will work best with python2.

**Comment by grandmoffgigi** [comment]
I am reverting to python2 right now then to see what if it fixes it.

**Comment by grandmoffgigi** [comment]
`python createDataset.py
Traceback (most recent call last):
  File "createDataset.py", line 1, in <module>
    import pandas as pd
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\__init__.py", line 13, in <module>
    __import__(dependency)
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 188
    exec(source_object, scope)
SyntaxError: unqualified exec is not allowed in function 'decorator' it is a nested function`
Went back to 2.7.8 and got this, can't find anything to fix it when searching it

**Comment by TotallyNotChase** [comment]
This seems to be a problem with the internal packages you've installed on your anaconda. The only thing I can suggest is you try with an individual edition anaconda, specifically anaconda2, or try a regular python2 installation.

**Comment by grandmoffgigi** [comment]
Ran into new issues with removing anaconda3 and 2 and reinstalling 2 since it doesn't work with a space in my name, I am trying to fix it now

**Comment by TotallyNotChase** [comment]
Do you mean issues with `createDataset.py` when you've a space in your name in the chatlogs? If so feel free to make a separate issue for that and I'll take a look.

I believe we can deduce that this was an issue on the anaconda side then. If you think this issue is resolved, please close it.

**Comment by grandmoffgigi** [comment]
Yeah it's anacondas issue now, can't run python since it's stuck in the deactivated conda environment and can't activate it since it doesn't like the space in my name
