### ISSUE TITLE
Seq2seq.py problem

### ISSUE THREAD

**Issue by artempal** [adeshpande3/Facebook-Messenger-Bot#8]
Hello!
I am get the problem in Seq2Seq.py:

> Traceback (most recent call last):
>   File "Seq2Seq.py", line 163, in <module>
>     numTrainingExamples, xTrain, yTrain = createTrainingMatrices('conversationDictionary.npy', wordList, maxEncoderLength)
>   File "Seq2Seq.py", line 43, in createTrainingMatrices
>     decoderMessage[valueIndex + 1] = wList.index('<EOS>')
> UnboundLocalError: local variable 'valueIndex' referenced before assignment

What can be wrong?
Thank you!

**Comment by artempal** [comment]
Removed the Russian language from the data. Only English-language messages. The error is different:
![deepinscreenshot_20171017173755](https://user-images.githubusercontent.com/23340672/31686665-70dbfdca-b38f-11e7-8385-aa6a279c9a8b.png)

**Comment by adeshpande3** [comment]
What are your values for numTrainingExamples and localBatchSize? Double check those to make sure that the args passed into randint are valid

**Comment by artempal** [comment]
Thanks.
numTrainingExamples = 22
localBatchSize = 24
22 - 24 - 1 = -3
As a result - a negative number.
