### ISSUE TITLE
Tensor Flow Error while running the flask server

### ISSUE THREAD

**Issue by Arvind6353** [adeshpande3/Facebook-Messenger-Bot#9]
Getting the below error when starting up the server:.
Please help

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [223,48
] rhs shape= [223,112]

 [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/rnn/embedding_wrapper/embed
ding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_rn
n_seq2seq/rnn/embedding_wrapper/embedding, save/RestoreV2_7)]]

**Comment by adeshpande3** [comment]
Like mentioned [here](https://github.com/adeshpande3/Facebook-Messenger-Bot/issues/6) this error means the saved model is different from the pre-trained model. Double check to make sure that the shapes of all your variables are the same as the graph you saved, same number of LSTM units, etc. Looks like your number of lstm units needs to be changed

**Comment by Arvind6353** [comment]
@adeshpande3  Thanks . It is working now with lstm as 48 units
